/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.WishlistCategoryController;
import Controller.WishlistController;
import java.awt.Color;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.List;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thia
 */
public class AddWishlistView extends javax.swing.JPanel {
    WishlistCategoryController wishlistCategoryController;
    WishlistController wishlistController;
    private final PropertyChangeSupport propChangeSupport = new PropertyChangeSupport(this);
    
    /**
     * Creates new form AddWishlist
     */
    public AddWishlistView() {
        this.wishlistController = new WishlistController();
        this.wishlistCategoryController = new WishlistCategoryController();
        initComponents();
    }
   
    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propChangeSupport.addPropertyChangeListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        wishlist_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        button_create = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        wishlist_categories = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wishlist_description = new javax.swing.JTextArea();
        err_mess = new javax.swing.JLabel();

        setBackground(new java.awt.Color(71, 85, 94));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name *");

        wishlist_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        wishlist_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                wishlist_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                wishlist_nameFocusLost(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category");

        button_create.setBackground(new java.awt.Color(131, 170, 211));
        button_create.setForeground(new java.awt.Color(255, 255, 255));
        button_create.setText("Create");
        button_create.setBorderPainted(false);
        button_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_createActionPerformed(evt);
            }
        });

        button_cancel.setBackground(new java.awt.Color(131, 170, 211));
        button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        button_cancel.setText("Cancel");
        button_cancel.setBorderPainted(false);
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        wishlist_categories.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        wishlist_categories.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = wishlistCategoryController.getAll().toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i];}
        });
        wishlist_categories.setToolTipText("");
        wishlist_categories.setFixedCellHeight(15);
        wishlist_categories.setFixedCellWidth(200);
        wishlist_categories.setFocusCycleRoot(true);
        wishlist_categories.setVisibleRowCount(5);
        jScrollPane2.setViewportView(wishlist_categories);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");

        wishlist_description.setColumns(20);
        wishlist_description.setRows(5);
        wishlist_description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        wishlist_description.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                wishlist_descriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                wishlist_descriptionFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(wishlist_description);

        err_mess.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_cancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(button_create)
                            .addGap(32, 32, 32))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2)))
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(wishlist_name)
                    .addComponent(jScrollPane1)
                    .addComponent(err_mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(err_mess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wishlist_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_create)
                    .addComponent(button_cancel))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_createActionPerformed
        String name = wishlist_name.getText().trim();

        if (!name.equals("")) {
            if(!wishlistController.nameIsTaken(name)) {
                String description = wishlist_description.getText().trim();
                List<String> categories_selected = wishlist_categories.getSelectedValuesList();
                System.out.println(categories_selected);
                wishlistController.newWishlist(name, description, categories_selected);
                propChangeSupport.firePropertyChange("btnWishlistAdded", false, true);
            } else {
                err_mess.setText("A wishlist already has this name.");
            }
        } else {
            wishlist_name.setBorder(new LineBorder(Color.red, 1));
        }
    }//GEN-LAST:event_button_createActionPerformed

    private void wishlist_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wishlist_nameFocusGained
        wishlist_name.setBorder(new LineBorder(Color.decode("#83AAD3"), 1));
    }//GEN-LAST:event_wishlist_nameFocusGained

    private void wishlist_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wishlist_nameFocusLost
        wishlist_name.setBorder(new LineBorder(Color.white, 1));
    }//GEN-LAST:event_wishlist_nameFocusLost

    private void wishlist_descriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wishlist_descriptionFocusGained
        wishlist_description.setBorder(new LineBorder(Color.decode("#83AAD3"), 1));
    }//GEN-LAST:event_wishlist_descriptionFocusGained

    private void wishlist_descriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wishlist_descriptionFocusLost
        wishlist_description.setBorder(new LineBorder(Color.white, 1));
    }//GEN-LAST:event_wishlist_descriptionFocusLost

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        propChangeSupport.firePropertyChange("btnCancel", false, true);
    }//GEN-LAST:event_button_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_create;
    private javax.swing.JLabel err_mess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> wishlist_categories;
    private javax.swing.JTextArea wishlist_description;
    private javax.swing.JTextField wishlist_name;
    // End of variables declaration//GEN-END:variables

    public void update() {
        removeAll();
        initComponents();
    }
}
