/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ItemController;
import Controller.WishlistCategoryController;
import Controller.WishlistController;
import Model.Wishlist;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Thia
 */
public class SeeWishlists extends javax.swing.JPanel {

    WishlistCategoryController wishlistCategoryController;
    WishlistController wishlistController;
    ItemController itemController;
    private final PropertyChangeSupport propChangeSupport = new PropertyChangeSupport(this);

    /**
     * Creates new form SeeWishlists
     */
    public SeeWishlists() {
        this.wishlistController = new WishlistController();
        this.wishlistCategoryController = new WishlistCategoryController();
        this.itemController = new ItemController();
        initComponents();
    }

    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbox_categories = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(71, 85, 94));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filter by category");
        jLabel2.setNextFocusableComponent(cbox_categories);

        cbox_categories.setModel(new javax.swing.DefaultComboBoxModel<>(wishlistCategoryController.getAll().toArray(new String[wishlistCategoryController.getAll().size()])));
        cbox_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_categoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbox_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(606, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbox_categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_categoriesActionPerformed
        Object selected = cbox_categories.getSelectedItem();
        // TP DE:LETE &*?*&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
    }//GEN-LAST:event_cbox_categoriesActionPerformed

    public void displayWishlists() {
        ArrayList<Wishlist> usersWishlists = wishlistController.getUsersWishlists();

        setLayout(null);

        for (int i = 0; i < usersWishlists.size(); i++) {

            final Integer wishlistId = usersWishlists.get(i).getId();
            ArrayList<Integer> wishlistCategoryIds = usersWishlists.get(i).getCategoryIds();

            JLabel wishlistName = new JLabel(usersWishlists.get(i).getName());
            wishlistName.setBounds(80, 150 + (i * 70), 200, 30);
            wishlistName.setOpaque(true);
            wishlistName.setFont(wishlistName.getFont().deriveFont(16.0f));
            wishlistName.setBackground(Color.decode("#47555E"));
            wishlistName.setForeground(Color.white);
            add(wishlistName);

            for (int j = 0; j < wishlistCategoryIds.size(); j++) {

                JLabel categoryName = new JLabel(wishlistCategoryController.getCategoryName(wishlistCategoryIds.get(j)));
                categoryName.setBounds(100 + (j * 100), 180 + (i * 70), 100, 30);
                categoryName.setOpaque(true);
                categoryName.setBackground(Color.decode("#47555E"));
                categoryName.setForeground(Color.white);
                add(categoryName);
            }

            JButton btnAddItem = new JButton();
            btnAddItem.setText("Add item");
            btnAddItem.setSize(100, 25);
            btnAddItem.setLocation(450, 165 + (i * 70));
            btnAddItem.setBackground(Color.decode("#83AAD3"));
            btnAddItem.setForeground(Color.white);
            btnAddItem.setBorderPainted(false);
            add(btnAddItem);

            btnAddItem.addActionListener((ActionEvent e) -> {
                propChangeSupport.firePropertyChange("btnAddItemClick", null, wishlistId);
            });

            JButton btnDelete = new JButton();
            btnDelete.setText("Delete");
            btnDelete.setBackground(Color.decode("#83AAD3"));
            btnDelete.setForeground(Color.white);
            btnDelete.setBorderPainted(false);
            btnDelete.setSize(100, 25);
            btnDelete.setLocation(555, 165 + (i * 70));
            add(btnDelete);

            btnDelete.addActionListener((ActionEvent e) -> {
                wishlistController.delete(wishlistId);
                propChangeSupport.firePropertyChange("btnDeleteWishlistClick", false, true);
                removeAll();
                initComponents();
                displayWishlists();
            });
        }

        JButton btnAddCat = new JButton();
        btnAddCat.setText("Add category");
        btnAddCat.setBackground(Color.decode("#83AAD3"));
        btnAddCat.setForeground(Color.white);
        btnAddCat.setBorderPainted(false);
        btnAddCat.setSize(150, 25);
        btnAddCat.setLocation(425, 81);
        add(btnAddCat);

        btnAddCat.addActionListener((ActionEvent e) -> {
            propChangeSupport.firePropertyChange("btnAddCategory", false, true);
        });

        JButton btnAddWishlist = new JButton();
        btnAddWishlist.setText("Create wishlist");
        btnAddWishlist.setBackground(Color.decode("#83AAD3"));
        btnAddWishlist.setForeground(Color.white);
        btnAddWishlist.setBorderPainted(false);
        btnAddWishlist.setSize(180, 25);
        btnAddWishlist.setLocation(625, 81);
        add(btnAddWishlist);

        btnAddWishlist.addActionListener((ActionEvent e) -> {
            propChangeSupport.firePropertyChange("btnAddWishlist", false, true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox_categories;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
