package View;

import Controller.ItemCategoryController;
import Controller.ItemController;
import Controller.WishlistController;
import Model.Item;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Thia
 */
public class WishlistView extends javax.swing.JPanel {

    ItemController itemController;
    ItemCategoryController itemCategoryController;
    Integer wishlistId;
    WishlistController wishlistController;
    private final PropertyChangeSupport propChangeSupport = new PropertyChangeSupport(this);

    /**
     * Creates new form WishlistView
     */
    public WishlistView() {
        this.itemController = new ItemController();
        this.itemCategoryController = new ItemCategoryController();
        this.wishlistController = new WishlistController();
        initComponents();
    }

    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(71, 85, 94));

        btn_back.setBackground(new java.awt.Color(131, 170, 211));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorderPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_back)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btn_back)
                .addContainerGap(524, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        propChangeSupport.firePropertyChange("btnBack", false, true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     *
     */
    public void displayItems() {

        Integer leftPadding = 300;
        Integer topPadding = 40;

        JLabel wishlistName = new JLabel(wishlistController.getName(wishlistId));
        wishlistName.setBounds(leftPadding, topPadding, 400, 30);
        wishlistName.setOpaque(true);
        wishlistName.setFont(wishlistName.getFont().deriveFont(20.0f));
        wishlistName.setBackground(Color.decode("#47555E"));
        wishlistName.setForeground(Color.white);
        add(wishlistName);

        JLabel wishlistDescription = new JLabel(wishlistController.getDescription(wishlistId));
        wishlistDescription.setBounds(leftPadding, topPadding + 10, 400, 80);
        wishlistDescription.setOpaque(true);
        wishlistDescription.setFont(wishlistDescription.getFont().deriveFont(12.0f));
        wishlistDescription.setBackground(Color.decode("#47555E"));
        wishlistDescription.setForeground(Color.white);
        add(wishlistDescription);

        setLayout(null);

        ArrayList<Item> wishlistItems = itemController.getWishlistItems(wishlistId);

        for (int i = 0; i < wishlistItems.size(); i++) {

            final Integer itemId = wishlistItems.get(i).getId();

            JLabel itemName = new JLabel(wishlistItems.get(i).getName());
            itemName.setBounds(leftPadding, 150 + (i * 70), 400, 30);
            itemName.setOpaque(true);
            itemName.setFont(itemName.getFont().deriveFont(16.0f));
            itemName.setBackground(Color.decode("#47555E"));
            itemName.setForeground(Color.white);
            add(itemName);

            JLabel categoryName = new JLabel(itemCategoryController.getCategoryName(wishlistItems.get(i).getCategoryId()));
            categoryName.setBounds(leftPadding + 20, 180 + (i * 70), 200, 30);
            categoryName.setOpaque(true);
            categoryName.setBackground(Color.decode("#47555E"));
            categoryName.setForeground(Color.white);
            add(categoryName);

            JButton btnDeleteFromWishlist = new JButton();
            btnDeleteFromWishlist.setText("X");
            btnDeleteFromWishlist.setBackground(Color.decode("#83AAD3"));
            btnDeleteFromWishlist.setForeground(Color.white);
            btnDeleteFromWishlist.setBorderPainted(false);
            btnDeleteFromWishlist.setSize(50, 25);
            btnDeleteFromWishlist.setLocation(leftPadding + 440, 165 + (i * 70));
            add(btnDeleteFromWishlist);

            btnDeleteFromWishlist.addActionListener((ActionEvent e) -> {
                itemController.deleteFromWishlist(wishlistId, itemId);
                propChangeSupport.firePropertyChange("btnDeleteItemFromWishlist", false, true);
                removeAll();
                initComponents();
                displayItems();
            });
        }
    }

    public void setWishlistId(Integer wishlistId) {
        this.wishlistId = wishlistId;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    // End of variables declaration//GEN-END:variables
}
